version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: monew-postgres
    environment:
      POSTGRES_DB: monew
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monew-net

  redis:
    image: redis:7
    container_name: monew-redis
    ports:
      - "6379:6379"
    networks:
      - monew-net

  mongo:
    image: mongo:6
    container_name: monew-mongo
    environment:
      MONGO_INITDB_DATABASE: monew
    ports:
      - "27017:27017"
    networks:
      - monew-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monew
    depends_on:
      - postgres
      - redis
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - monew-net

volumes:
  postgres_data:

networks:
  monew-net: