version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: monew-postgres
    environment:
      POSTGRES_DB: monew
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monew-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2g
        reservations:
          cpus: "2.0"
          memory: 1g

  redis:
    image: redis:7
    container_name: monew-redis
    ports:
      - "6379:6379"
    networks:
      - monew-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m

  mongo:
    image: mongo:6
    container_name: monew-mongo
    environment:
      MONGO_INITDB_DATABASE: monew
    ports:
      - "27017:27017"
    networks:
      - monew-net
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1g

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monew-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      mongo:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monew
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/monew
      SPRING_DATA_REDIS_HOST: redis
      BATCH_TRIGGER_ENABLED: true
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: always
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g
    ports:
      - "8080:8080"
      - "1327:1327"
    networks:
      - monew-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - monew-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monew-net

volumes:
  postgres_data:
  grafana_data:

networks:
  monew-net:
    name: monew-net
